import { Bellefair } from 'next/font/google'
import './globals.scss'

// components

const bellefair = Bellefair({ subsets: ['latin'], weight: ["400"] })

export const metadata = {
  title: 'Create Dv App',
  description: 'Generated by dvelat codes',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={bellefair.className}>
        {children}
      </body>
    </html>
  )
}
